/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Userspace loader + monitor for scx_fresh.
 *
 * Build expects build/scx_fresh.skel.h generated by bpftool.
 */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <limits.h>
#include <stdarg.h>

#include <bpf/libbpf.h>
#include <bpf/bpf.h>

#include "../include/scx_fresh_shared.h"
#include "scx_fresh.skel.h"

static volatile sig_atomic_t g_exiting;

static void on_sigint(int signo)
{
    (void)signo;
    g_exiting = 1;
}

static int bump_memlock_rlimit(void)
{
    struct rlimit r = {RLIM_INFINITY, RLIM_INFINITY};
    return setrlimit(RLIMIT_MEMLOCK, &r);
}

static int libbpf_print_fn(enum libbpf_print_level level,
                           const char *format, va_list args)
{
    if (level == LIBBPF_DEBUG)
        return 0;
    return vfprintf(stderr, format, args);
}

static int handle_evt(void *ctx, void *data, size_t data_sz)
{
    (void)ctx;

    if (data_sz < sizeof(struct fresh_evt))
        return 0;

    const struct fresh_evt *e = (const struct fresh_evt *)data;

    if (e->kind == FRESH_EVT_STAGE_ENQUEUE) {
        if (data_sz < sizeof(struct fresh_stage_enqueue_evt))
            return 0;
        const struct fresh_stage_enqueue_evt *est = data;
        printf("[stage_enqueue] ts_ns=%llu pid_tgid=%llu job=%llu stage=%u "
               "release_ns=%llu deadline_ns=%llu enq_flags=0x%llx dsq=0x%llx "
               "slice_ns=%llu vruntime=%llu exec_ns=%llu policy=%u cpu=%u overrun=%u state_present=%u\n",
               (unsigned long long)e->ts_ns, (unsigned long long)e->pid_tgid,
               (unsigned long long)e->job_id, e->stage_id,
               (unsigned long long)e->release_ts_ns, (unsigned long long)e->deadline_ts_ns,
               (unsigned long long)est->enq_flags, (unsigned long long)est->dsq_id,
               (unsigned long long)est->slice_ns, (unsigned long long)est->vruntime,
               (unsigned long long)e->exec_ns_in_job, est->policy, est->cpu,
               est->overrun, est->state_present);
        return 0;
    }

    if (e->kind == FRESH_EVT_URGENT_ENQUEUE) {
        if (data_sz < sizeof(struct fresh_urgent_enqueue_evt))
            return 0;
        const struct fresh_urgent_enqueue_evt *urgent = data;
        printf("[urgent_enqueue] ts_ns=%llu pid_tgid=%llu job=%llu stage=%u "
               "release_ns=%llu deadline_ns=%llu enq_flags=0x%llx dsq=0x%llx "
               "policy=%u cpu=%u wakeup=%u late=%u hint_present=%u\n",
               (unsigned long long)e->ts_ns, (unsigned long long)e->pid_tgid,
               (unsigned long long)e->job_id, e->stage_id,
               (unsigned long long)e->release_ts_ns, (unsigned long long)e->deadline_ts_ns,
               (unsigned long long)urgent->enq_flags, (unsigned long long)urgent->dsq_id,
               urgent->policy, urgent->cpu, urgent->wakeup, urgent->late, urgent->hint_present);
        return 0;
    }

    const char *kind = "UNKNOWN";
    switch (e->kind) {
    case FRESH_EVT_DEADLINE_MISS:  kind = "DEADLINE_MISS"; break;
    case FRESH_EVT_BUDGET_OVERRUN: kind = "BUDGET_OVERRUN"; break;
    case FRESH_EVT_STALE_DEMOTION: kind = "STALE_DEMOTION"; break;
    case FRESH_EVT_BUDGET_DEMOTION: kind = "BUDGET_DEMOTION"; break;
    default: break;
    }

    printf("[evt] %s stage=%u job=%llu pid_tgid=0x%llx age=%.3fms exec=%.3fms "
           "ts_ns=%llu release_ns=%llu deadline_ns=%llu\n",
           kind,
           e->stage_id,
           (unsigned long long)e->job_id,
           (unsigned long long)e->pid_tgid,
           (double)e->age_ns / 1e6,
           (double)e->exec_ns_in_job / 1e6,
           (unsigned long long)e->ts_ns, (unsigned long long)e->release_ts_ns,
           (unsigned long long)e->deadline_ts_ns);
    return 0;
}

static const char *blocking_syscall(uint64_t id)
{
    if (id == (uint64_t)-1) return "none";
    if (id == SYS_clock_nanosleep) return "clock_nanosleep";
    if (id == SYS_nanosleep) return "nanosleep";
    if (id == SYS_futex) return "futex";
    if (id == SYS_exit || id == SYS_exit_group) return "exit";
    return "other";
}

static void print_execution_task(const char *prefix, const struct fresh_execution_task *t)
{
    /* Hex comm is lossless and cannot inject delimiters or new log lines. */
    printf(" %s_key=%llu %s_policy=%u %s_stage=%u %s_slice_ns=%llu "
           "%s_last_dsq=%llu %s_insert_ns=%llu %s_requested_slice_ns=%llu %s_comm_hex=",
           prefix, (unsigned long long)t->pid_tgid, prefix, t->policy,
           prefix, t->stage, prefix, (unsigned long long)t->slice_ns,
           prefix, (unsigned long long)t->last_insert_dsq,
           prefix, (unsigned long long)t->last_insert_ns,
           prefix, (unsigned long long)t->requested_slice_ns, prefix);
    for (size_t i = 0; i < sizeof(t->comm); i++)
        printf("%02x", (unsigned char)t->comm[i]);
}

static int handle_execution_evt(void *ctx, void *data, size_t size)
{
    (void)ctx;
    if (size != sizeof(struct fresh_execution_evt)) return -EINVAL;
    const struct fresh_execution_evt *e = data;
    printf("[execution] kind=%u ts_ns=%llu urgent_key=%llu cpu=%u runnable=%u preempt=%u "
           "prev_state=%llu callback_delta_ns=%llu syscall_id=%llu syscall=%s",
           e->kind, (unsigned long long)e->ts_ns, (unsigned long long)e->urgent_pid_tgid,
           e->cpu, e->runnable, e->preempt, (unsigned long long)e->prev_state,
           (unsigned long long)e->callback_delta_ns, (unsigned long long)e->syscall_id,
           blocking_syscall(e->syscall_id));
    print_execution_task("task", &e->task);
    print_execution_task("next", &e->next);
    putchar('\n');
    return 0;
}

static int print_execution_stats(struct scx_fresh_bpf *skel)
{
    int ncpu = libbpf_num_possible_cpus();
    if (ncpu < 1) return -EINVAL;
    struct fresh_execution_stats *values = calloc(ncpu, sizeof(*values));
    if (!values) return -ENOMEM;
    uint32_t key = 0;
    int err = bpf_map_lookup_elem(bpf_map__fd(skel->maps.execution_stats), &key, values);
    struct fresh_execution_stats sum = {};
    if (!err) {
        for (int cpu = 0; cpu < ncpu; cpu++) {
            sum.emitted += values[cpu].emitted;
            sum.lost += values[cpu].lost;
            sum.identity_conflicts += values[cpu].identity_conflicts;
        }
        printf("execution_summary: emitted=%llu lost=%llu identity_conflicts=%llu\n",
               (unsigned long long)sum.emitted, (unsigned long long)sum.lost,
               (unsigned long long)sum.identity_conflicts);
    }
    free(values);
    return err;
}

static void usage(const char *argv0)
{
    fprintf(stderr,
            "Usage: %s (--pin <dir> | --print-ops-flags)\n"
            "  --print-ops-flags: inspect embedded BPF flags without loading or attaching\n"
            "  --print-config: inspect flags and selected probe options without attaching\n"
            "  --urgent-preempt wakeup|always: opt-in preemption probe (default wakeup)\n"
            "  --deadline-grace-us N: late-demotion grace in microseconds (default 1000)\n"
            "  --be-slice-cap-us N: BE/unhinted insertion slice cap (default 0 = off)\n"
            "  --trace-urgent: sampled enqueue events and unsampled counters (default off)\n"
            "  --trace-stage N: unsampled enqueue lanes for application stage N for perf correlation (default off)\n"
            "  --trace-worker-name NAME: worker comm for execution trace and urgent diagnostics\n"
            "  --trace-execution-cpu N: switch/wakeup/syscall and URGENT callback probe (default off)\n"
            "\n"
            "Example:\n"
            "  sudo %s --pin /sys/fs/bpf/scx_fresh\n",
            argv0, argv0);
}

static int print_urgent_trace_stats(struct scx_fresh_bpf *skel)
{
    int ncpu = libbpf_num_possible_cpus();
    if (ncpu < 1)
        return -EINVAL;
    struct fresh_urgent_trace_stats *values = calloc(ncpu, sizeof(*values));
    if (!values)
        return -ENOMEM;
    uint32_t key = 0;
    int err = bpf_map_lookup_elem(bpf_map__fd(skel->maps.urgent_trace_stats), &key, values);
    if (err) {
        free(values);
        return err;
    }
    struct fresh_urgent_trace_stats sum = {};
    for (int cpu = 0; cpu < ncpu; cpu++) {
#define FRESH_ADD_COUNTER(name) sum.name += values[cpu].name;
        FRESH_URGENT_COUNTER_FIELDS(FRESH_ADD_COUNTER)
#undef FRESH_ADD_COUNTER
    }
    printf("urgent_trace_summary:");
#define FRESH_PRINT_COUNTER(name) printf(" " #name "=%llu", (unsigned long long)sum.name);
    FRESH_URGENT_COUNTER_FIELDS(FRESH_PRINT_COUNTER)
#undef FRESH_PRINT_COUNTER
    printf("\n");
    free(values);
    return 0;
}

static int print_stage_trace_stats(struct scx_fresh_bpf *skel)
{
    int ncpu = libbpf_num_possible_cpus();
    if (ncpu < 1)
        return -EINVAL;
    struct fresh_stage_trace_stats *values = calloc(ncpu, sizeof(*values));
    if (!values)
        return -ENOMEM;
    uint32_t key = 0;
    int err = bpf_map_lookup_elem(bpf_map__fd(skel->maps.stage_trace_stats), &key, values);
    if (!err) {
        struct fresh_stage_trace_stats sum = {};
        for (int cpu = 0; cpu < ncpu; cpu++) {
            sum.enqueues += values[cpu].enqueues;
            sum.emitted += values[cpu].emitted;
            sum.lost += values[cpu].lost;
        }
        printf("stage_trace_summary: enqueues=%llu emitted=%llu lost=%llu\n",
               (unsigned long long)sum.enqueues, (unsigned long long)sum.emitted,
               (unsigned long long)sum.lost);
    }
    free(values);
    return err;
}

static int ensure_dir(const char *dir)
{
    struct stat st;
    if (!stat(dir, &st)) {
        if (S_ISDIR(st.st_mode))
            return 0;
        return -ENOTDIR;
    }
    if (mkdir(dir, 0755))
        return -errno;
    return 0;
}

int main(int argc, char **argv)
{
    const char *pin_dir = NULL;
    int print_ops_flags = 0;
    int print_config = 0;
    int preempt_always = 0;
    int trace_urgent = 0;
    int trace_stage = 0;
    uint32_t stage_id = FRESH_STAGE_UNSPECIFIED;
    const char *worker_name = "";
    int execution_cpu = -1;
    uint64_t deadline_grace_us = 1000;
    uint64_t be_slice_cap_us = 0;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--pin") && i + 1 < argc) {
            pin_dir = argv[++i];
        } else if (!strcmp(argv[i], "--print-ops-flags")) {
            print_ops_flags = 1;
        } else if (!strcmp(argv[i], "--print-config")) {
            print_config = 1;
        } else if (!strcmp(argv[i], "--trace-urgent")) {
            trace_urgent = 1;
        } else if (!strcmp(argv[i], "--trace-stage") && i + 1 < argc) {
            const char *value = argv[++i];
            char *end = NULL;
            errno = 0;
            unsigned long long parsed = strtoull(value, &end, 10);
            if (errno || !*value || strspn(value, "0123456789") != strlen(value) ||
                !end || *end || parsed > UINT32_MAX) {
                fprintf(stderr, "invalid trace stage: %s\n", value);
                return 1;
            }
            trace_stage = 1;
            stage_id = (uint32_t)parsed;
        } else if (!strcmp(argv[i], "--trace-worker-name") && i + 1 < argc) {
            worker_name = argv[++i];
            if (!*worker_name || strlen(worker_name) >= 16) {
                fprintf(stderr, "trace worker name must contain 1 to 15 bytes\n");
                return 1;
            }
        } else if ((!strcmp(argv[i], "--deadline-grace-us") ||
                    !strcmp(argv[i], "--be-slice-cap-us")) && i + 1 < argc) {
            int is_cap = !strcmp(argv[i], "--be-slice-cap-us");
            char *end = NULL;
            const char *value = argv[++i];
            errno = 0;
            unsigned long long parsed = strtoull(value, &end, 10);
            if (errno || !*value || strspn(value, "0123456789") != strlen(value) ||
                !end || *end || parsed > UINT64_MAX / 1000ULL) {
                fprintf(stderr, "invalid %s: %s\n",
                        is_cap ? "BE slice cap" : "deadline grace", value);
                return 1;
            }
            if (is_cap)
                be_slice_cap_us = (uint64_t)parsed;
            else
                deadline_grace_us = (uint64_t)parsed;
        } else if (!strcmp(argv[i], "--trace-execution-cpu") && i + 1 < argc) {
            char *end = NULL;
            errno = 0;
            const char *value = argv[++i];
            long parsed = strtol(value, &end, 10);
            if (errno || !*value || *end || parsed < 0 || parsed > INT_MAX) {
                fprintf(stderr, "invalid execution trace CPU: %s\n", value);
                return 1;
            }
            execution_cpu = (int)parsed;
        } else if (!strcmp(argv[i], "--urgent-preempt") && i + 1 < argc) {
            const char *mode = argv[++i];
            if (strcmp(mode, "wakeup") && strcmp(mode, "always")) {
                fprintf(stderr, "invalid URGENT preemption probe: %s\n", mode);
                return 1;
            }
            preempt_always = !strcmp(mode, "always");
        } else if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
            usage(argv[0]);
            return 0;
        } else {
            usage(argv[0]);
            return 1;
        }
    }

    if ((!pin_dir && !print_ops_flags && !print_config) ||
        (pin_dir && (print_ops_flags || print_config)) || (print_ops_flags && print_config)) {
        usage(argv[0]);
        return 1;
    }
    if (execution_cpu >= 0 && !*worker_name) {
        fprintf(stderr, "execution tracing requires --trace-worker-name\\n");
        return 1;
    }

    libbpf_set_strict_mode(LIBBPF_STRICT_ALL);
    libbpf_set_print(libbpf_print_fn);

    struct scx_fresh_bpf *skel = scx_fresh_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }

    skel->rodata->urgent_preempt_always = preempt_always;
    skel->rodata->trace_urgent_enqueues = trace_urgent;
    skel->rodata->trace_stage_enqueues = trace_stage;
    skel->rodata->trace_stage_id = stage_id;
    memcpy((void *)skel->rodata->trace_worker_name, worker_name, strlen(worker_name) + 1);
    skel->rodata->execution_trace_cpu = execution_cpu;
    skel->rodata->deadline_grace_ns = deadline_grace_us * 1000ULL;
    skel->rodata->be_slice_cap_ns = be_slice_cap_us * 1000ULL;
    if (execution_cpu < 0)
        bpf_map__set_max_entries(skel->maps.execution_events, 4096);
    /* No tracepoint load or attachment requirement for ordinary runs. */
    bpf_program__set_autoload(skel->progs.trace_execution_switch, execution_cpu >= 0);
    bpf_program__set_autoload(skel->progs.trace_execution_wakeup, execution_cpu >= 0);
    bpf_program__set_autoload(skel->progs.trace_execution_sys_enter, execution_cpu >= 0);
    bpf_program__set_autoload(skel->progs.trace_execution_sys_exit, execution_cpu >= 0);
    if (print_ops_flags || print_config) {
        if (print_ops_flags)
            printf("0x%llx\n", skel->struct_ops.scx_fresh_ops->flags);
        else
            printf("ops_flags=0x%llx urgent_preempt=%s trace_urgent=%u execution_cpu=%d "
                   "trace_stage=%u deadline_grace_us=%llu be_slice_cap_us=%llu\n",
                   skel->struct_ops.scx_fresh_ops->flags,
                   skel->rodata->urgent_preempt_always ? "always" : "wakeup",
                   skel->rodata->trace_urgent_enqueues, execution_cpu, trace_stage,
                   (unsigned long long)deadline_grace_us,
                   (unsigned long long)be_slice_cap_us);
        scx_fresh_bpf__destroy(skel);
        return 0;
    }

    if (bump_memlock_rlimit()) {
        perror("setrlimit(RLIMIT_MEMLOCK)");
        /* keep going; some distros don't need this */
    }

    int err = ensure_dir(pin_dir);
    if (err) {
        fprintf(stderr, "Failed to create pin dir %s: %s\n", pin_dir, strerror(-err));
        goto out;
    }

    printf("Loading scheduler with ops_flags=0x%llx urgent_preempt=%s trace_urgent=%u execution_cpu=%d "
           "trace_stage=%u deadline_grace_us=%llu be_slice_cap_us=%llu\n",
           skel->struct_ops.scx_fresh_ops->flags,
           preempt_always ? "always" : "wakeup", trace_urgent, execution_cpu, trace_stage,
           (unsigned long long)deadline_grace_us,
           (unsigned long long)be_slice_cap_us);
    err = scx_fresh_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to load BPF skeleton: %s\n", strerror(-err));
        goto out;
    }

    err = scx_fresh_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF scheduler: %s\n", strerror(-err));
        goto out;
    }

    /* Pin maps so libfreshqos and other processes can access them. */
    char path[4096];

    snprintf(path, sizeof(path), "%s/task_hints", pin_dir);
    err = bpf_map__pin(skel->maps.task_hints, path);
    if (err) {
        fprintf(stderr, "Failed to pin task_hints: %s\n", strerror(-err));
        goto out;
    }

    snprintf(path, sizeof(path), "%s/events", pin_dir);
    err = bpf_map__pin(skel->maps.events, path);
    if (err) {
        fprintf(stderr, "Failed to pin events: %s\n", strerror(-err));
        goto out;
    }

    struct ring_buffer *rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
                                              handle_evt, NULL, NULL);
    if (!rb) {
        fprintf(stderr, "Failed to create ring buffer\n");
        err = -ENOMEM;
        goto out;
    }
    if (execution_cpu >= 0) {
        err = ring_buffer__add(rb, bpf_map__fd(skel->maps.execution_events), handle_execution_evt, NULL);
        if (err) {
            ring_buffer__free(rb);
            goto out;
        }
    }

    signal(SIGINT, on_sigint);
    signal(SIGTERM, on_sigint);

    printf("scx_fresh attached. Maps pinned under: %s\n", pin_dir);
    printf("Press Ctrl-C to stop.\n");

    while (!g_exiting) {
        err = ring_buffer__poll(rb, 100 /*ms*/);
        if (err == -EINTR) {
            err = 0;
            break;
        }
        if (err < 0) {
            fprintf(stderr, "ring_buffer__poll: %s\n", strerror(-err));
            break;
        }
    }

    /* The harness stops this loader only after its demo has exited. Flush
     * remaining diagnostic events before printing the full unsampled counts.
     */
    /* Stop CPU-wide producers before flushing and taking their final counts. */
    if (execution_cpu >= 0)
        scx_fresh_bpf__detach(skel);
    int consume_err = ring_buffer__consume(rb);
    if (consume_err < 0) err = consume_err;
    if (trace_urgent && print_urgent_trace_stats(skel)) {
        fprintf(stderr, "failed to read URGENT trace counters\n");
        err = -EIO;
    }
    if (trace_stage && print_stage_trace_stats(skel)) {
        fprintf(stderr, "failed to read stage trace counters\n");
        err = -EIO;
    }
    if (execution_cpu >= 0 && print_execution_stats(skel)) {
        fprintf(stderr, "failed to read execution trace counters\n");
        err = -EIO;
    }
    ring_buffer__free(rb);

out:
    scx_fresh_bpf__destroy(skel);
    return err ? 1 : 0;
}
